# -*- coding: utf-8 -*-
"""Customer Churn Analysis System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GF48gnA3AM7aTiL6e7s3ZQLgitZriVo7

Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""Generate Synthetic Dataset"""

np.random.seed(42)

n = 100000

df = pd.DataFrame({
    "Customer_ID": np.arange(1, n+1),
    "Age": np.random.randint(18, 71, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Tenure": np.random.randint(0, 11, n),
    "Balance": np.random.randint(0, 200001, n),
    "CreditScore": np.random.randint(300, 901, n),
    "EstimatedSalary": np.random.randint(10000, 150001, n),
    "NumOfProducts": np.random.randint(1, 5, n),
    "IsActiveMember": np.random.choice(["Yes", "No"], n),
    "Churn": np.random.choice([0, 1], n, p=[0.7, 0.3])
})

print(df.head())

"""Data Cleaning & Preprocessing"""

print("\nMissing Values:\n", df.isnull().sum())

print("\nData Types:\n", df.dtypes)

df["Gender"] = df["Gender"].map({"Male": 0, "Female": 1})
df["IsActiveMember"] = df["IsActiveMember"].map({"No": 0, "Yes": 1})

"""Descriptive Statistics"""

print("\nMean:\n", df.mean(numeric_only=True))

print("\nMedian:\n", df.median(numeric_only=True))

print("\nMode:\n", df.mode().iloc[0])

print("\nStandard Deviation:\n", df.std(numeric_only=True))

"""Churn Analysis"""

print("\nChurn Count:\n", df["Churn"].value_counts())

print("\nChurn Percentage:\n", df["Churn"].value_counts(normalize=True)*100)

"""Group-Based Analysis"""

print("\nGender vs Churn:\n", df.groupby("Gender")["Churn"].mean())

print("\nActive vs Churn:\n", df.groupby("IsActiveMember")["Churn"].mean())

print("\nProducts vs Churn:\n", df.groupby("NumOfProducts")["Churn"].mean())

df["AgeGroup"] = pd.cut(df["Age"], bins=[18,25,35,50,70],
                       labels=["18-25","26-35","36-50","50+"])

print("\nAge Group vs Churn:\n", df.groupby("AgeGroup")["Churn"].mean())

"""Relationship Analysis"""

print("\nCorrelation:\n", df.corr(numeric_only=True))

"""Data Visualization

Bar Plot
"""

sns.countplot(x="Churn", data=df)
plt.title("Churn Count")
plt.show()



"""Pie Chart"""

df["Churn"].value_counts().plot.pie(autopct="%1.1f%%")
plt.title("Churn Distribution")
plt.show()

"""Histogram"""

df["Age"].hist(bins=30)
plt.title("Age Distribution")
plt.show()

"""Box Plot"""

sns.boxplot(x="Churn", y="Balance", data=df)
plt.title("Balance vs Churn")
plt.show()

"""Scatter Plot"""

plt.scatter(df["CreditScore"], df["Balance"], alpha=0.3)
plt.title("Credit Score vs Balance")
plt.xlabel("CreditScore")
plt.ylabel("Balance")
plt.show()

"""Heatmap"""

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()